"""Add comments table

Revision ID: 4d59e7c1d2d2
Revises: 3f23a042939d
Create Date: 2025-10-22 02:36:58.774173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d59e7c1d2d2'
down_revision: Union[str, None] = '3f23a042939d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
