"""extend currency field

Revision ID: e760f26d0db8
Revises: 89a20061b621
Create Date: 2025-10-22 23:05:08.949362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e760f26d0db8'
down_revision: Union[str, None] = '89a20061b621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'enrollments', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'lessons', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    # ### end Alembic commands ###
